# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atributo', '0002_auto_20171215_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atributo',
            name='tipo_atributo',
            field=models.IntegerField(choices=[(1, 'Texto'), (2, 'Numeral'), (3, 'Decimal'), (4, 'Percentual Inteiro'), (5, 'Percentual Decimal')]),
        ),
    ]
