# Generated by Django 2.0 on 2018-06-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atributo', '0003_auto_20171221_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atributo',
            name='valor_maximo_atributo',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='atributo',
            name='valor_minimo_atributo',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
