# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-16 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atributo', '0002_auto_20171215_1205'),
        ('subatributo', '0004_auto_20171215_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atributo_subatributo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_relacao_atributo_subatributo', models.IntegerField(choices=[(1, 'Intervalos/Multiplicadores'), (2, 'Percentual')])),
                ('intervalo_atributo_subatributo', models.CharField(max_length=150, null=True)),
                ('multiplicador_atributo_subatributo', models.CharField(max_length=150, null=True)),
                ('fk_id_atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atributo.Atributo')),
                ('fk_id_subatributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subatributo.Subatributo')),
            ],
        ),
    ]
