# Generated by Django 2.0 on 2018-06-23 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
        ('atributo_subatributo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atributo_subatributo',
            name='fk_id_sistema',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sistema.Sistema'),
            preserve_default=False,
        ),
    ]
