# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subatributo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subatributo',
            name='valor_inicial',
            field=models.IntegerField(choices=[(1, 'Sim'), (2, 'N\xe3o')]),
        ),
    ]
