# Generated by Django 2.0 on 2017-12-22 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Narracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_narracao', models.CharField(max_length=150)),
                ('fk_id_sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Sistema')),
            ],
        ),
    ]
