# Generated by Django 2.0 on 2018-06-24 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subatributo', '0005_auto_20171221_2033'),
        ('atributo', '0003_auto_20171221_2033'),
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_calculo', models.IntegerField(choices=[(1, 'Intervalos/Multiplicadores'), (2, 'Percentual')])),
                ('intervalo_calculo', models.CharField(max_length=150, null=True)),
                ('multiplicador_calculo', models.CharField(max_length=150, null=True)),
                ('fk_id_atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atributo.Atributo')),
                ('fk_id_sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Sistema')),
                ('fk_id_subatributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subatributo.Subatributo')),
            ],
        ),
    ]
