# Generated by Django 2.0 on 2017-12-22 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('narracao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_ficha', models.CharField(max_length=150)),
                ('fk_id_narracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='narracao.Narracao')),
            ],
        ),
    ]
