# Generated by Django 2.0 on 2018-06-27 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subatributo', '0005_auto_20171221_2033'),
        ('atributo', '0003_auto_20171221_2033'),
        ('ficha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha_atributo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_atributo', models.CharField(max_length=10)),
                ('fk_id_atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atributo.Atributo')),
                ('fk_id_ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.Ficha')),
            ],
        ),
        migrations.CreateModel(
            name='Ficha_subatributo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_subatributo', models.CharField(max_length=10)),
                ('fk_id_ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.Ficha')),
                ('fk_id_subatributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subatributo.Subatributo')),
            ],
        ),
    ]
