# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
        ('atributo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_atributo', models.CharField(max_length=150)),
                ('tipo_atributo', models.IntegerField(choices=[(1, b'Texto'), (2, b'Numeral'), (3, b'Decimal'), (4, b'Percentual Inteiro'), (5, b'Percentual Decimal')])),
                ('valor_minimo_atributo', models.IntegerField()),
                ('valor_maximo_atributo', models.IntegerField()),
                ('fk_id_sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Sistema')),
            ],
        ),
        migrations.RemoveField(
            model_name='atributos',
            name='fk_id_sistema',
        ),
        migrations.DeleteModel(
            name='Atributos',
        ),
    ]
