# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subatributo', '0003_auto_20171215_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subatributo',
            name='valor_inicial',
        ),
        migrations.AddField(
            model_name='subatributo',
            name='valor_inicial_subatributo',
            field=models.IntegerField(choices=[(1, 'Sim'), (2, 'N\xe3o')], default=0),
            preserve_default=False,
        ),
    ]
